# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm
      MONGO_INITDB_ROOT_PASSWORD: adm

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongodb_exp
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: adm
      ME_CONFIG_MONGODB_ADMINPASSWORD: adm
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
